In [271]:
import pandas as pd
import os

In [272]:
os.getcwd()
#cwd used to  get direction to the working directory

'c:\\Users\\Alivinne\\OneDrive\\Desktop\\workshop'

In [273]:
df=pd.read_csv('datasets/student_performance_project_dataset (1).csv')
# varies from excel,csv,jason,API,database #name is case sensitive #df used to define the variables

In [274]:

df.head()

,Student_ID,Gender,Age,School_Type,Region,Attendance,Study_Hours,Final_Score,Internet_Access,Overall_Grade
0,S1000,Male,16.0,NaN,West,-5.0,7.3,33.0,Yes,A
1,S1001,FEMALE,16.0,Private,West,64.0,NaN,NaN,NaN,E
2,S1002,male,15.0,Public,North,NaN,10.2,-10.0,no,B
3,S1003,M,-1.0,PRIVATE,North,-5.0,NaN,78.0,NaN,E
4,S1004,FEMALE,-1.0,Private,North,95.0,1.4,57.0,no,E

In [275]:
df.shape
#rows,columns

(1500, 10)

In [276]:
list(df.columns)
#used to get the different names of the columns

['Student_ID',
 'Gender',
 'Age',
 'School_Type',
 'Region',
 'Attendance',
 'Study_Hours',
 'Final_Score',
 'Internet_Access',
 'Overall_Grade']

In [277]:
df.info()
#used to show the data types, number of columns ,index(rows),not null

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Student_ID       1500 non-null   str
 1   Gender           1287 non-null   str
 2   Age              1307 non-null   float64
 3   School_Type      1214 non-null   str
 4   Region           1500 non-null   str
 5   Attendance       1128 non-null   float64
 6   Study_Hours      988 non-null    float64
 7   Final_Score      1107 non-null   float64
 8   Internet_Access  1174 non-null   str
 9   Overall_Grade    1318 non-null   str
dtypes: float64(4), str(6)
memory usage: 117.3 KB

In [278]:
import numpy as np
df.select_dtypes(include='number')
df.select_dtypes(include=['object'])

C:\Users\Alivinne\AppData\Local\Temp\ipykernel_3280\3014059131.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=['object'])

     Student_ID  Gender School_Type Region Internet_Access Overall_Grade
0         S1000    Male         NaN   West             Yes             A
1         S1001  FEMALE     Private   West             NaN             E
2         S1002    male      Public  North             no              B
3         S1003       M    PRIVATE   North             NaN             E
4         S1004  FEMALE     Private  North             no              E
...         ...     ...         ...    ...             ...           ...
1495      S1005    male         NaN   West             Yes             D
1496      S2004    male      public   West             Yes             D
1497      S1354    Male      public  South             YES             F
1498      S1378       F    PRIVATE   North             NaN             F
1499      S1224  Female      Public  South             NaN             C

[1500 rows x 6 columns]

In [279]:
df.describe()
#focuses on the numerical part of the data set

               Age   Attendance  Study_Hours  Final_Score
count  1307.000000  1128.000000   988.000000  1107.000000
mean     28.726855    59.474291     5.461336    51.137308
std      37.021325    46.808311    10.872988    50.984336
min      -1.000000    -5.000000    -3.000000   -10.000000
25%      15.000000    -5.000000    -3.000000   -10.000000
50%      17.000000    77.000000    -3.000000    55.000000
75%      19.000000   105.000000    13.625000   110.000000
max     120.000000   105.000000    30.000000   110.000000

In [280]:
df.isnull().values.any()

np.True_

In [281]:
df.isnull().sum()

Student_ID           0
Gender             213
Age                193
School_Type        286
Region               0
Attendance         372
Study_Hours        512
Final_Score        393
Internet_Access    326
Overall_Grade      182
dtype: int64

In [282]:
df.isnull().sum().sum()

np.int64(2477)

In [283]:
df["Final_Score"].isnull().sum()

np.int64(393)

In [284]:
df[
    df.isnull().any(axis=1)
    ]

,Student_ID,Gender,Age,School_Type,Region,Attendance,Study_Hours,Final_Score,Internet_Access,Overall_Grade
0,S1000,Male,16.0,NaN,West,-5.0,7.3,33.0,Yes,A
1,S1001,FEMALE,16.0,Private,West,64.0,NaN,NaN,NaN,E
2,S1002,male,15.0,Public,North,NaN,10.2,-10.0,no,B
3,S1003,M,-1.0,PRIVATE,North,-5.0,NaN,78.0,NaN,E
5,S1005,M,NaN,NaN,South,-5.0,NaN,54.0,NaN,D
...,...,...,...,...,...,...,...,...,...,...
1494,S2169,female,-1.0,PRIVATE,Central,NaN,NaN,110.0,NaN,NaN
1495,S1005,male,17.0,NaN,West,78.0,-3.0,NaN,Yes,D
1497,S1354,Male,15.0,public,South,NaN,NaN,NaN,YES,F
1498,S1378,F,18.0,PRIVATE,North,53.0,-3.0,110.0,NaN,F
1499,S1224,Female,NaN,Public,South,105.0,NaN,93.0,NaN,C

In [285]:
df.isnull().sum()

Student_ID           0
Gender             213
Age                193
School_Type        286
Region               0
Attendance         372
Study_Hours        512
Final_Score        393
Internet_Access    326
Overall_Grade      182
dtype: int64

In [286]:
df.shape

(1500, 10)

In [318]:
df = df.dropna().reset_index(drop=True)

In [317]:
df.dropna

<bound method DataFrame.dropna of     Student_ID  Gender   Age School_Type   Region  Attendance  Study_Hours  \
0        S1004  Female  17.0     Private    North        95.0          1.4
1        S1016  Female  15.0      Public     West        54.0         25.8
2        S1019  Female  17.0      Public  Central         0.0         13.9
3        S1024  Female  19.0     Private     East         0.0          0.0
4        S1029  Female  16.0     Private    South       100.0          0.0
..         ...     ...   ...         ...      ...         ...          ...
226      S2472    Male  19.0      Public     West         0.0          0.0
227      S2479    Male  17.0      Public     West         0.0          5.3
228      S2484    Male  17.0     Private  Central         0.0          6.3
229      S1484    Male  17.0      Public  Central         0.0         21.1
230      S2004    Male  17.0      Public     West       100.0          3.9

     Final_Score Internet_Access Overall_Grade
0           57.0              No             E
1          100.0              No             C
2           76.0             Yes             B
3            0.0             Yes             A
4          100.0             Yes             E
..           ...             ...           ...
226          0.0             Yes             F
227         58.0             Yes             A
228        100.0             Yes             C
229        100.0             Yes             E
230        100.0             Yes             D

[231 rows x 10 columns]>

In [289]:
df.shape

(231, 10)

In [290]:
df.isnull().sum().sum()

np.int64(0)

In [315]:
df.dropna

<bound method DataFrame.dropna of     Student_ID  Gender   Age School_Type   Region  Attendance  Study_Hours  \
0        S1004  Female  17.0     Private    North        95.0          1.4
1        S1016  Female  15.0      Public     West        54.0         25.8
2        S1019  Female  17.0      Public  Central         0.0         13.9
3        S1024  Female  19.0     Private     East         0.0          0.0
4        S1029  Female  16.0     Private    South       100.0          0.0
..         ...     ...   ...         ...      ...         ...          ...
226      S2472    Male  19.0      Public     West         0.0          0.0
227      S2479    Male  17.0      Public     West         0.0          5.3
228      S2484    Male  17.0     Private  Central         0.0          6.3
229      S1484    Male  17.0      Public  Central         0.0         21.1
230      S2004    Male  17.0      Public     West       100.0          3.9

     Final_Score Internet_Access Overall_Grade
0           57.0              No             E
1          100.0              No             C
2           76.0             Yes             B
3            0.0             Yes             A
4          100.0             Yes             E
..           ...             ...           ...
226          0.0             Yes             F
227         58.0             Yes             A
228        100.0             Yes             C
229        100.0             Yes             E
230        100.0             Yes             D

[231 rows x 10 columns]>

In [313]:
df.duplicated().any()

np.False_

In [293]:
df.duplicated().sum()

np.int64(0)

In [294]:

df = df.drop_duplicates(subset='Student_ID', keep='first').reset_index(drop=True)

In [295]:
nrow = len(df)
nrow

231

In [296]:
df["Gender"] = (
df["Gender"].fillna("Unknown").astype(str).str.strip().str.lower().apply(
lambda x: "Male" if x.startswith("m")
else "Female" if x.startswith("f")
else "Unknown")
)
df["Gender"].value_counts()

Gender
Female    123
Male      108
Name: count, dtype: int64

In [311]:
df["Gender"].value_counts()
df["School_Type"].value_counts()
df["Internet_Access"].value_counts()
df["School_Type"].value_counts()
df["Internet_Access"].value_counts()

Internet_Access
Yes    119
No     112
Name: count, dtype: int64

In [297]:
df["School_Type"] = (
    df["School_Type"]
    .fillna("Unknown")
    .astype(str)
    .str.strip()
    .str.lower()
    .map(
        lambda x: "Public" if "public" in x
        else "Private" if "priv" in x
        else "Unknown"
    )
)

df["School_Type"].value_counts()

School_Type
Private    121
Public     110
Name: count, dtype: int64

In [312]:
df["Internet_Access"] = (
df["Internet_Access"]
    .fillna("Unknown")
    .astype(str)
    .str.strip()
    .str.lower()
    .map(
        lambda x: "Yes" if x.startswith("y") else "No" if x.startswith("n") else "Unknown"
    )
)

In [299]:
df[c] = (
    df[c]
    .fillna("Unknown")
    .astype(str)
    .str.strip()
    .str.upper()
)

df[c].value_counts()

Overall_Grade
A    65
D    38
C    34
B    34
E    33
F    27
Name: count, dtype: int64

In [300]:
df.copy()


for col in text_cols:
    df[col] = df[col].fillna("Unknown").astype(str).str.strip()

df["Region"] = df["Region"].str.title()
df["Overall_Grade"] = df["Overall_Grade"].str.upper()

df.head()

,Student_ID,Gender,Age,School_Type,Region,Attendance,Study_Hours,Final_Score,Internet_Access,Overall_Grade
0,S1004,Female,-1.0,Private,North,95.0,1.4,57.0,No,E
1,S1016,Female,15.0,Public,West,54.0,25.8,110.0,No,C
2,S1019,Female,17.0,Public,Central,-5.0,13.9,76.0,Yes,B
3,S1024,Female,19.0,Private,East,-5.0,-3.0,-10.0,Yes,A
4,S1029,Female,16.0,Private,South,105.0,-3.0,110.0,Yes,E

In [301]:

df = df.copy()

df["Student_ID"] = df["Student_ID"].astype(str)
for col in ["Gender", "School_Type", "Region", "Internet_Access", "Overall_Grade"]:
    df[col] = df[col].astype("category")

for col in ["Age", "Attendance", "Study_Hours", "Final_Score"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df.info()

def glimpse(df_=None):
    if df_ is None:
        df_ = df
    print(f"Rows: {df_.shape[0]}, Columns: {df_.shape[1]}")
    print(df_.dtypes)
    print(df_.head())
glimpse()

<class 'pandas.DataFrame'>
RangeIndex: 231 entries, 0 to 230
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Student_ID       231 non-null    str
 1   Gender           231 non-null    category
 2   Age              231 non-null    float64
 3   School_Type      231 non-null    category
 4   Region           231 non-null    category
 5   Attendance       231 non-null    float64
 6   Study_Hours      231 non-null    float64
 7   Final_Score      231 non-null    float64
 8   Internet_Access  231 non-null    category
 9   Overall_Grade    231 non-null    category
dtypes: category(5), float64(4), str(1)
memory usage: 10.4 KB
Rows: 231, Columns: 10
Student_ID              str
Gender             category
Age                 float64
School_Type        category
Region             category
Attendance          float64
Study_Hours         float64
Final_Score         float64
Internet_Access    category
Overall_Grade      category
dtype: object
  Student_ID  Gender   Age School_Type   Region  Attendance  Study_Hours  \
0      S1004  Female  -1.0     Private    North        95.0          1.4
1      S1016  Female  15.0      Public     West        54.0         25.8
2      S1019  Female  17.0      Public  Central        -5.0         13.9
3      S1024  Female  19.0     Private     East        -5.0         -3.0
4      S1029  Female  16.0     Private    South       105.0         -3.0

   Final_Score Internet_Access Overall_Grade
0         57.0              No             E
1        110.0              No             C
2         76.0             Yes             B
3        -10.0             Yes             A
4        110.0             Yes             E

In [302]:
df = df.copy()

# Age: replace values outside [10, 25] with median of valid ages
valid_age_mask = df["Age"].between(10, 25)
age_median = df.loc[valid_age_mask, "Age"].median()
df["Age"] = df["Age"].where(valid_age_mask, age_median)

# Attendance: clamp to [0, 100]
df["Attendance"] = df["Attendance"].clip(lower=0, upper=100)

# Study_Hours: set negative values to 0
df["Study_Hours"] = df["Study_Hours"].clip(lower=0)

# Final_Score: clamp to [0, 100]
df["Final_Score"] = df["Final_Score"].clip(lower=0, upper=100)

df[["Age", "Attendance", "Study_Hours", "Final_Score"]].describe()


summary = df[["Age", "Attendance", "Study_Hours", "Final_Score"]].describe()
summary

              Age  Attendance  Study_Hours  Final_Score
count  231.000000  231.000000   231.000000   231.000000
mean    16.969697   58.051948     7.095238    54.177489
std      1.213668   42.588291     9.637798    43.204354
min     15.000000    0.000000     0.000000     0.000000
25%     16.000000    0.000000     0.000000     0.000000
50%     17.000000   72.000000     0.000000    62.000000
75%     18.000000  100.000000    13.650000   100.000000
max     19.000000  100.000000    29.900000   100.000000

In [303]:
def cap_outliers(x):
    q = x.quantile([0.01, 0.99])
    return x.clip(lower=q.iloc[0], upper=q.iloc[1])

df["Attendance"] = cap_outliers(df["Attendance"])
df["Study_Hours"] = cap_outliers(df["Study_Hours"])
df["Final_Score"] = cap_outliers(df["Final_Score"])

df["Attendance"] = cap_outliers(df["Attendance"])
df["Study_Hours"] = cap_outliers(df["Study_Hours"])
df["Final_Score"] = cap_outliers(df["Final_Score"])

In [304]:
df.to_csv("student_performance_cleaned.csv", index=False)

In [305]:
df.shape

(231, 10)

In [319]:
df.isna().sum()

Student_ID         0
Gender             0
Age                0
School_Type        0
Region             0
Attendance         0
Study_Hours        0
Final_Score        0
Internet_Access    0
Overall_Grade      0
dtype: int64

In [ ]:
!git --version

NameError: name 'git' is not defined